Fix Windows MSVC build
- Add cross platform intrinsic wrappers
- Fix MSVC "error C2036: 'void *': unknown size" errors, which are allowed on GCC/Clang with an extension. From the C Standard 6.2.5-27: A pointer to void shall have the same representation and alignment requirements as a pointer to a character type.
- Disable MSVC warnings in CMakeLists.txt files
- Add .editorconfig files to enforce 4 spaces for indentation
- Add gensln.bat to conveniently generate Visual Studio solution.